### ISSUE TITLE
Support of Discovering Connected Devices ?

### ISSUE THREAD

**Issue by dudusandi** [sahilchaddha/homebridge-magichome-platform#1]
Any way to auto discovery or set by hostname ? My router doesn't have mode to keep same ip devices and I can't set static ip on controllers led.

**Comment by sahilchaddha** [comment]
Hey @dudusandi ,

Currently the plugin doesn't support discovering of devices.
But Yes we can discover connected MagicHome devices. 

I will work on this implementation in my free time.
Expect this feature to be in upcoming `v1.2.0`
Maybe we can use MAC Address instead of IP to reference to lights.

Meanwhile if you like the plugin, please star, watch the repository to support the development.
Thanks

**Comment by dudusandi** [comment]
Using MAC would solve the problem, thank you very much.

**Comment by sahilchaddha** [comment]
Hey @dudusandi ,
I have updated the plugin. You can use MAC instead of IP. MAC should be in format of `XXXXXXXXXXXX`.

Due to lack of time, i was not able to test it thoroughly.
Would love if you can test `v1.2.0` version and provide your feedback/suggestions.

Thanks

**Comment by sahilchaddha** [comment]
Fixed in `v1.2.0`

**Comment by dudusandi** [comment]
> Hey @dudusandi ,
> I have updated the plugin. You can use MAC instead of IP. MAC should be in format of `XXXXXXXXXXXX`.
> 
> Due to lack of time, i was not able to test it thoroughly.
> Would love if you can test `v1.2.0` version and provide your feedback/suggestions.
> 
> Thanks

I tested and it works perfectly with MAC, Thanks. Does this search every 30s use a lot of resources or not?

**Comment by dudusandi** [comment]
![captura de tela 2018-10-23 as 15 21 25](https://user-images.githubusercontent.com/41707380/47381861-5d835180-d6d7-11e8-8cdd-4c17ffa2fc81.png)
 I noticed this problem in the log, but I do not understand what it is

**Comment by sahilchaddha** [comment]
@dudusandi I am glad that new version of the plugin fixed your issue.
The logs you are seeing is because of `node-persist` plugin. We use this plugin to cache IP:MAC Address mapping in case homebridge restarts or breaks.

I will debug this issue and you can expect a fix in upcoming version.
Meanwhile you can ignore the logs, since they are not a blocker and does not interfere with fundamental features of the plugin.

**Comment by sahilchaddha** [comment]
@dudusandi 

I have added a potential fix for `Unhandled Rejection` logs occuring due to `node-persist`.
Please try updating the plugin to `1.2.2`. 

The issue should be fixed, and you should not see any error logs.
Enjoy your Lights
Thanks

**Comment by dudusandi** [comment]
> @dudusandi
> 
> I have added a potential fix for `Unhandled Rejection` logs occuring due to `node-persist`.
> Please try updating the plugin to `1.2.3`.
> 
> The issue should be fixed, and you should not see any error logs.
> Enjoy your Lights
> Thanks

![captura de tela 2018-10-24 as 15 30 45](https://user-images.githubusercontent.com/41707380/47453039-0bf3c900-d7a2-11e8-90cb-8d4b14ee6081.png)

**Comment by sahilchaddha** [comment]
Hey @dudusandi 
Looks like you need to install `git` on your raspberry pi. 
Nevermind, looks like `node-persist` is causing lots of issues. 
I will try to refactor the code and remove this dependency.
I will try to cache the IP:MAC Address using native node api instead of `node-persist`

**Comment by dudusandi** [comment]
> 
> 
> Hey @dudusandi
> Looks like you need to install `git` on your raspberry pi.
> Nevermind, looks like `node-persist` is causing lots of issues.
> I will try to refactor the code and optimize this dependency.

If I can help with anything, just ask.

**Comment by sahilchaddha** [comment]
@dudusandi Thanks for your support.
You can test version `1.2.4`.
Hope it resolves your issue.

**Comment by dudusandi** [comment]
> 
> 
> @dudusandi Thanks for your support.
> You can test version `1.2.4`.
> Hope it resolves your issue.

Testing here, apparently perfect.

**Comment by sahilchaddha** [comment]
Glad to hear that.
